#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      brew cask install zerotier-one
      ;;
    *)
      curl -s https://install.zerotier.com/ | ${NOSUDO} sudo bash
      ;;
  esac

}

main "$@"
