#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.zerotier')" == "$ZEROTIER_VERSION" ]]; then
    return 0
  fi

  if ! sysctl 2>/dev/null; then
    return 0
  fi

  return 1
}

main "$@"
