#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.zerotier')" == "$ZEROTIER_VERSION" ]]; then
    return 0
  fi

  case "${DISTRIB_ID}" in
    Darwin)
      true
      ;;
    *)
      if ! sysctl 2>/dev/null; then
        return 0
      fi
      ;;
  esac

  return 1
}

main "$@"
