#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_zerotier="$(zt -v 2>/dev/null || true)"
  jq -n --arg zerotier "$ver_zerotier" '{zerotier: $zerotier}'
}

version "$@"
