#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_zerotier="0.0.1"
  jq -n --arg zerotier "$ver_zerotier" '{zerotier: $zerotier}'
}

version "$@"
